#include "display_font.h"

static const uint32_t fontTable[] = {
//  INPUT     SEGMENT
//  CHAR      A       B       C       D       E       F       G       H       K       M       N       P       R       S       T       U
    [ '0' ] = SEG_A | SEG_B | SEG_C | SEG_D | SEG_E | SEG_F | SEG_G | SEG_H,
    [ '1' ] =                 SEG_C | SEG_D,
    [ '2' ] = SEG_A | SEG_B | SEG_C |         SEG_E | SEG_F | SEG_G |                                 SEG_P |                         SEG_U,
    [ '3' ] = SEG_A | SEG_B | SEG_C | SEG_D | SEG_E | SEG_F |                                         SEG_P |                         SEG_U,
    [ '4' ] =                 SEG_C | SEG_D |                         SEG_H |                         SEG_P |                         SEG_U,
    [ '5' ] = SEG_A | SEG_B |         SEG_D | SEG_E | SEG_F |         SEG_H |                         SEG_P |                         SEG_U,
    [ '6' ] = SEG_A | SEG_B |         SEG_D | SEG_E | SEG_F | SEG_G | SEG_H |                         SEG_P |                         SEG_U,
    [ '7' ] = SEG_A | SEG_B | SEG_C | SEG_D,
    [ '8' ] = SEG_A | SEG_B | SEG_C | SEG_D | SEG_E | SEG_F | SEG_G | SEG_H |                         SEG_P |                         SEG_U,
    [ '9' ] = SEG_A | SEG_B | SEG_C | SEG_D | SEG_E | SEG_F |         SEG_H |                         SEG_P |                         SEG_U,
    [ '<' ] =                                                                                 SEG_N |         SEG_R,
    [ '>' ] =                                                                 SEG_K |                                         SEG_T,
    [ 'A' ] = SEG_A | SEG_B | SEG_C | SEG_D |                 SEG_G | SEG_H |                         SEG_P |                         SEG_U,
    [ 'B' ] = SEG_A | SEG_B | SEG_C | SEG_D | SEG_E | SEG_F |                         SEG_M |         SEG_P |         SEG_S,
    [ 'C' ] = SEG_A | SEG_B |                 SEG_E | SEG_F | SEG_G | SEG_H,
    [ 'D' ] = SEG_A | SEG_B | SEG_C | SEG_D | SEG_E | SEG_F |                         SEG_M |                         SEG_S,
    [ 'E' ] = SEG_A | SEG_B |                 SEG_E | SEG_F | SEG_G | SEG_H |                         SEG_P |                         SEG_U,
    [ 'F' ] = SEG_A | SEG_B |                                 SEG_G | SEG_H |                         SEG_P |                         SEG_U,
    [ 'G' ] = SEG_A | SEG_B |         SEG_D | SEG_E | SEG_F | SEG_G | SEG_H |                         SEG_P,
    [ 'H' ] =                 SEG_C | SEG_D |                 SEG_G | SEG_H |                         SEG_P |                         SEG_U,
    [ 'I' ] = SEG_A | SEG_B |                 SEG_E | SEG_F |                         SEG_M |                         SEG_S,
    [ 'J' ] = SEG_A | SEG_B |                         SEG_F | SEG_G |                 SEG_M |                         SEG_S,
    [ 'K' ] =                                                 SEG_G | SEG_H |                 SEG_N |         SEG_R |                 SEG_U,
    [ 'L' ] =                                 SEG_E | SEG_F | SEG_G | SEG_H,
    [ 'M' ] =                 SEG_C | SEG_D |                 SEG_G | SEG_H | SEG_K |         SEG_N,
    [ 'N' ] =                 SEG_C | SEG_D |                 SEG_G | SEG_H | SEG_K |                         SEG_R,
    [ 'O' ] = SEG_A | SEG_B | SEG_C | SEG_D | SEG_E | SEG_F | SEG_G | SEG_H,
    [ 'P' ] = SEG_A | SEG_B | SEG_C |                         SEG_G | SEG_H |                         SEG_P |                         SEG_U,
    [ 'Q' ] = SEG_A | SEG_B | SEG_C | SEG_D | SEG_E | SEG_F | SEG_G | SEG_H |                                 SEG_R,
    [ 'R' ] = SEG_A | SEG_B | SEG_C |                         SEG_G | SEG_H |                         SEG_P | SEG_R |                 SEG_U,
    [ 'S' ] = SEG_A | SEG_B |         SEG_D | SEG_E | SEG_F |         SEG_H |                         SEG_P |                         SEG_U,
    [ 'T' ] = SEG_A | SEG_B |                                                         SEG_M |                         SEG_S,  
    [ 'U' ] =                 SEG_C | SEG_D | SEG_E | SEG_F | SEG_G | SEG_H,
    [ 'V' ] =                                                 SEG_G | SEG_H |         SEG_M |                                 SEG_T,
    [ 'W' ] =                 SEG_C | SEG_D |                                                                 SEG_R |         SEG_T,
    [ 'X' ] =                                                                 SEG_K |         SEG_N |         SEG_R |         SEG_T,
    [ 'Y' ] =                                                                 SEG_K |         SEG_N |                 SEG_S,
    [ 'Z' ] = SEG_A | SEG_B |                                 SEG_G | SEG_H |                 SEG_N |                         SEG_T,
};